# Site settings
title: Luke Carlisle
baseurl: ""
url: ""

# Build settings
markdown: kramdown

collections:
  - videos

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - gulpfile.js
  - package.json
