backend:
  name: github
  repo : moyden/lukecarlisle2
  branch: master

media_folder: images

collections:
  - name: "videos"
    label: "Videos"
    folder: "_videos"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Vimeo Link", name: "vimeo", widget: "string"}
      - {label: "Display Order", name: "order", widget: "number"}
